name: Build testing docker image
on:
  push:
    paths:
      - 'pyproject.toml'
      - '.github/workflows/ci-image-build.yml'
      - '.github/docker/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Log into Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build docker image
        run: |
          docker build -f .github/docker/Dockerfile -t ghcr.io/hemagso/thundera:python3.11 .
      
      - name: Push docker image
        run: |
          docker push ghcr.io/hemagso/thundera:python3.11